version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=hackathon
      - POSTGRES_USER=ozimiz
      - POSTGRES_PASSWORD=123

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
